import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { articles, categories, statusLabels } from './data/articles'
import './styles.css'

const nav = ['Home', 'Articles', 'About', 'Disclaimer', 'Suggest Correction']
const sectionOrder = ['Коротко','Кому нужно','Что понадобится','Куда обращаться','Пошагово','Частые ошибки','Официальный источник','Предупреждение']
const Icon = ({children}) => <span aria-hidden="true" className="icon">{children}</span>
function statusClass(status) { return status === 'verified' ? 'status verified' : status === 'needs_update' ? 'status update' : 'status draft' }
function routeTo(page, articleId) { window.history.pushState({}, '', articleId ? `#/${page}/${articleId}` : `#/${page}`); window.dispatchEvent(new Event('popstate')) }
function useRoute() { const [hash, setHash] = useState(location.hash || '#/Home'); React.useEffect(() => { const on = () => setHash(location.hash || '#/Home'); addEventListener('popstate', on); return () => removeEventListener('popstate', on) }, []); const [, page='Home', articleId] = hash.split('/'); return { page, articleId } }
function label(n){return {Home:'Главная',Articles:'Статьи',About:'О проекте',Disclaimer:'Дисклеймер','Suggest Correction':'Предложить исправление'}[n]}
function Header() { const [open,setOpen]=useState(false); return <header className="site-header"><div className="header-inner"><button onClick={()=>routeTo('Home')} className="brand focus-ring"><span className="brand-mark">✓</span><span><strong>Greece Guide</strong><small>Официально. Просто. Бесплатно.</small></span></button><nav className="desktop-nav">{nav.map(n=><button key={n} onClick={()=>routeTo(n)} className="nav-btn focus-ring">{label(n)}</button>)}</nav><button className="menu-btn focus-ring" onClick={()=>setOpen(!open)} aria-label="Открыть меню">{open?'×':'☰'}</button></div>{open&&<div className="mobile-nav">{nav.map(n=><button key={n} onClick={()=>{routeTo(n);setOpen(false)}}>{label(n)}</button>)}</div>}</header> }
function SearchBox({query,setQuery}){return <label className="search-label"><span>Поиск по справочнику</span><div className="search-box"><Icon>🔎</Icon><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Например: ΑΜΚΑ, ΑΦΜ, gov.gr"/></div></label>}
function ArticleCard({article}){return <article className="card motion-card"><div className="badges"><span className="category-badge">{article.category}</span><span className={statusClass(article.status)}>{statusLabels[article.status]}</span></div><h3>{article.title}</h3><p>{article.summary}</p><dl><dt>Последняя проверка</dt><dd>{article.lastChecked}</dd><dt>Источник</dt><dd>{article.sourceName}</dd></dl><button onClick={()=>routeTo('Article',article.id)} className="primary-btn focus-ring">Открыть статью</button></article>}
function CategoryGrid(){return <section><h2>Разделы</h2><div className="category-grid">{categories.map(c=><button key={c} onClick={()=>routeTo('Articles')} className="category-card focus-ring"><Icon>📄</Icon>{c}</button>)}</div></section>}
function Home(){const [q,setQ]=useState(''); const filtered=articles.filter(a=>(a.title+a.summary+a.category).toLowerCase().includes(q.toLowerCase())); return <><section className="hero"><div className="container"><p className="eyebrow">Для жителей Греции, пожилых людей и иностранцев</p><h1>Греческие процедуры простым человеческим языком</h1><p className="hero-text">Мы объясняем, где искать официальную информацию, какие шаги проверить и как не попасть на неофициальные сайты.</p><SearchBox query={q} setQuery={setQ}/></div></section><main className="container main-space"><CategoryGrid/><h2>Популярные статьи</h2><div className="cards-grid">{filtered.map(a=><ArticleCard key={a.id} article={a}/>)}</div></main></>}
function ArticlesPage(){const [q,setQ]=useState(''); const [cat,setCat]=useState('Все'); const list=articles.filter(a=>(cat==='Все'||a.category===cat)&&(a.title+a.summary).toLowerCase().includes(q.toLowerCase())); return <main className="container page"><h1>Статьи</h1><SearchBox query={q} setQuery={setQ}/><div className="filters">{['Все',...categories].map(c=><button key={c} onClick={()=>setCat(c)} className={cat===c?'active':''}>{c}</button>)}</div><div className="cards-grid">{list.map(a=><ArticleCard key={a.id} article={a}/>)}</div></main>}
function ArticleDetail({id}){const a=articles.find(x=>x.id===id)||articles[0]; return <main className="container article-page"><button onClick={()=>routeTo('Articles')} className="back-btn focus-ring">← Все статьи</button><h1>{a.title}</h1><div className="badges"><span className={statusClass(a.status)}>{statusLabels[a.status]}</span><span className="category-badge">Проверено: {a.lastChecked}</span></div>{sectionOrder.map(s=><section key={s} className="content-section"><h2>{s}</h2><p className={s==='Предупреждение'?'warning-text':''}>{a.sections[s]}</p></section>)}<div className="article-actions"><a href={a.sourceUrl} target="_blank" rel="noreferrer" className="primary-btn focus-ring">Открыть источник ↗</a><button onClick={()=>routeTo('Suggest Correction')} className="secondary-btn focus-ring">Предложить исправление</button></div></main>}
function SimplePage({type}){const map={About:['О проекте','Greece Guide помогает читать официальные процедуры проще. Проект не заменяет государственные сайты и не даёт юридических консультаций.'],Disclaimer:['Дисклеймер','Информация носит справочный характер. Перед действием проверяйте актуальные требования на официальном сайте. Статус «Проверено» ставит только владелец проекта после ручной проверки.'],'Suggest Correction':['Предложить исправление','Нашли ошибку? Подготовьте ссылку на официальный источник и описание проблемы. Публикация изменений возможна только после ручной проверки владельца проекта.']}; const [h,p]=map[type]; return <main className="container page narrow"><h1>{h}</h1><p className="lead">{p}</p><div className="notice"><Icon>⚠️</Icon><strong>Используйте только официальные источники:</strong> gov.gr, efka.gov.gr, ypergasias.gov.gr, aade.gr, dypa.gov.gr, eopyy.gov.gr, migration.gov.gr, stratologia.gr и сайты Δήμος.</div></main>}
function App(){const {page,articleId}=useRoute(); return <><Header/>{page==='Articles'?<ArticlesPage/>:page==='Article'?<ArticleDetail id={articleId}/>:['About','Disclaimer','Suggest Correction'].includes(page)?<SimplePage type={page}/>:<Home/>}<footer>Greece Guide — бесплатный справочник. Не является юридической консультацией.</footer></>}
createRoot(document.getElementById('root')).render(<App />)
